name: Frontend Deploy

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsLakituRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Check formatting
        run: |
          cd frontend
          npm run format:check

      - name: Lint code
        run: |
          cd frontend
          npm run lint

      - name: Build frontend
        run: |
          cd frontend
          echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
          echo "VITE_COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }}" >> .env
          echo "VITE_COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}" >> .env
          echo "VITE_COGNITO_DOMAIN=${{ secrets.COGNITO_DOMAIN }}" >> .env
          npm run build

      - name: Upload to S3
        run: |
          aws s3 sync frontend/dist/ s3://${{ secrets.SITE_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
